function [transmitters] = get_transmitters_from_cells(selected_phone_cells, frequency)
    for i = 1:length(selected_phone_cells)
        lat = selected_phone_cells(i).lat;
        lon = selected_phone_cells(i).lon;
        channel = randi(20)-1;
        transmitters(i) = txsite("Name","Small cell transmitter", ...
        "Latitude",lat, ...
        "Longitude",lon, ...
        "AntennaHeight",10, ...
        "TransmitterPower",5, ...
        "TransmitterFrequency",frequency('3')+channel*20e6);
    end
end

