function [outputArg1,outputArg2] = plot_values_map(transmitters, datalats, datalons, data)
% Show txsites. If Site Viewer is already open, keep current camera view.
if isViewerInitiallyVisible && ~viewer.Visible
    return % Abort if Site Viewer has been closed
end
if isViewerInitiallyVisible
    showAnimation = 'none';
else
    showAnimation = 'zoom';
end
show(transmitters,'Map',viewer,'Animation',showAnimation, ...
    'AntennaSiteCoordinates', txsCoords);
% Show busy message overlay. Use cleanup object to hide message overlay if
% a forced exit occurs (error or Ctrl-C).
onForcedExit = rfprop.internal.onExit(@()hideBusyMessage(viewer));
viewer.showBusyMessage(message('shared_channel:rfprop:SINRMapBusyMessage').getString);

visualType = 'sinr';
values = -5:20;
contourmap(transmitters, datalats, datalons, data, visualType, ...
    'Animation', animation, ...
    'Map', viewer, ...
    'Levels', values, ...
    'ColorLimits', clim, ...
    'Colormap', cmap, ...
    'Transparency', transparency, ...
    'ShowLegend', showLegend, ...
    'ImageSize', imageSize, ...
    'MaxRange', maxrange, ...
    'LegendTitle', message('shared_channel:rfprop:SINRLegendTitle').getString, ...
    'SaturateColorFloor', true, ...
    'AntennaSiteCoordinates', txsCoords);

end

