tx_st = txsite("Name","Small cell transmitter", ...
    "Latitude",37.184481, ...
    "Longitude",-3.617047, ...
    "AntennaHeight",10, ...
    "TransmitterPower",5, ...
    "TransmitterFrequency",28e9);

rx_st = rxsite("Name","Small cell receiver", ...
    "Latitude",37.184471, ...
    "Longitude",-3.617057, ...
    "AntennaHeight",1);

map = siteviewer('Buildings', 'map.osm');

raytrace(tx_st,rx_st,"NumReflections",[0 1 2], ...
    "Type","pathloss", ...
    "ColorLimits",[80 130])

